# Generated by Django 2.1.5 on 2019-01-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20190128_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.CharField(default='', max_length=50),
        ),
    ]
