# Generated by Django 2.1.5 on 2019-02-08 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_delete_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraspField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GraspModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='graspfield',
            name='grasp_model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.GraspModel'),
        ),
    ]
